POS_APP/Controllers/ImportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS_APP.Models;

namespace POS_APP.Controllers
{
    public class ImportsController : Controller
    {
        // GET: Imports
        private POS_DBEntities db = new POS_DBEntities();
        // GET: Imports
        public ActionResult Index()
        {
            ViewBag.PCode = new SelectList(db.Products, "PCode", "PName");
            ViewBag.CatId = new SelectList(db.Categories, "CatId", "CatName");
            ViewBag.SupId = new SelectList(db.Suppliers, "SupId", "SupName");
            return View();
        }
        public JsonResult GetAllData()
        {
            var imports = (from a in db.Imports
                           join b in db.Products on a.PCode equals b.PCode
                           join c in db.Categories on a.CatId equals c.CatId
                           join d in db.Suppliers on a.SupId equals d.SupId
                           select new
                           {
                               a.ImportID,
                               a.PCode,
                               a.CatId,
                               a.SupId,
                               a.ImportDate,
                               a.ImportQTY,
                               b.PName,
                               c.CatName,
                               d.SupName
                           });
            return new JsonResult { Data = imports, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult Create(Import import)
        {
            db.Imports.Add(import);
            db.SaveChanges();
            return new JsonResult { Data = "Insert Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //get by id
        public JsonResult GetDataID(int? id)
        {
            var import = (from a in db.Imports
                          join b in db.Products on a.PCode equals b.PCode
                          join c in db.Categories on a.CatId equals c.CatId
                          join d in db.Suppliers on a.SupId equals d.SupId
                          where (a.ImportID == id)
                          select new
                          {
                              a.ImportID,
                              a.PCode,
                              a.CatId,
                              a.SupId,
                              a.ImportDate,
                              a.ImportQTY,
                              b.PName,
                              c.CatName,
                              d.SupName
                          });
            return new JsonResult { Data = import, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Update
        public JsonResult Edit(Import import)
        {
            db.Entry(import).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return new JsonResult { Data = "Update Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Delete
        public JsonResult Delete(int id)
        {
            Import Import = db.Imports.Find(id);
            db.Imports.Remove(Import);
            db.SaveChanges();
            return new JsonResult { Data = "Delete Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

POS_APP/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS_APP.Models;

namespace POS_APP.Controllers
{
    public class ReportsController : Controller
    {
       // GET: Reports
        private POS_DBEntities db = new POS_DBEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaleReport()
        {
            return View();
        }
        public ActionResult StockReport()
        {
            return View();
        }

        //SaleProduct
        public JsonResult SaleProduct(DateTime date1, DateTime date2)
        {
            var result = from a in db.Products
                         join b in db.Sales on a.PCode equals b.PCode
                         where b.SaleDate >= date1 && b.SaleDate <= date2
                         select new
                         {
                             b.SaleID,
                             b.SaleDate,
                             a.PName,
                             b.SalePrice,
                             b.SaleQty
                         };
            return new JsonResult { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }



        //Remain
        public JsonResult RemainByQTY()
        {
            var Imports = from a in db.Products
                          join b in db.Imports on a.PCode equals b.PCode
                          group b by new { a.PCode, a.PName } into g
                          select new
                          {
                              PCode = g.Key.PCode,
                              PName = g.Key.PName,
                              TotalQTY = g.Sum(x => x.ImportQTY)
                          };
            var Sales = from a in db.Products
                        join b in db.Sales on a.PCode equals b.PCode
                        group b by new { a.PCode, a.PName } into g
                        select new
                        {
                            PCode = g.Key.PCode,
                            PName = g.Key.PName,
                            TotalQTY = g.Sum(x => x.SaleQty)
                        };
            var result = from a in Imports
                         join b in Sales on a.PCode equals b.PCode
                         select new
                         {
                             a.PCode,
                             a.PName,
                             Import = a.TotalQTY,
                             SaleOut = b.TotalQTY,
                             Remain = a.TotalQTY - b.TotalQTY
                         };
            return new JsonResult { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}
    

POS_APP/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS_APP.Models;

namespace POS_APP.Controllers
{
    public class SalesController : Controller
    {
        // GET: Sales
        private POS_DBEntities db = new POS_DBEntities();
        // GET: Sales
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetProducts(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                return new JsonResult
                {
                    Data = db.Products.Where(s => s.PName.Contains(search)),
                    JsonRequestBehavior =
               JsonRequestBehavior.AllowGet
                };
            }
            return new JsonResult
            {
                Data = db.Products.ToList(),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
        //SaveAll
        public JsonResult SaveAll(Sale[] arr)
        {
            foreach (var sale in arr)
            {
                sale.SaleDate = DateTime.Now;
                db.Sales.Add(sale);
                db.SaveChanges();
            }
            return new JsonResult { Data = "Sale Success!!", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

POS_APP/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS_APP.Models;

namespace POS_APP.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        private POS_DBEntities db = new POS_DBEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserList()
        {
            return View();
        }
        //GetAllData
        public JsonResult GetAllData()
        {
            return new JsonResult { Data = db.Users.ToList(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Insert
        public JsonResult Create(User user)
        {
            //Upload Image
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    var filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/"), filename);
                    user.Image = filename;
                    file.SaveAs(path);
                }
            }
            db.Users.Add(user);
            db.SaveChanges();
            return new JsonResult { Data = "Insert Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //get by id
        public JsonResult GetDataID(int? id)
        {
            User user = db.Users.Find(id);
            return new JsonResult { Data = user, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Update
        public JsonResult Edit(User user)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                if (file != null && file.ContentLength > 0)
                {
                    var filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images/"), filename);
                    user.Image = filename;
                    file.SaveAs(path);
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }
            else
            {
                //double check
                db.Entry(user).State = EntityState.Modified;
                db.Entry(user).Property(x => x.Image).IsModified = false;
                db.SaveChanges();
            }
            return new JsonResult { Data = "Update Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Delete
        public JsonResult Delete(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return new JsonResult { Data = "Delete Success", JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        //Login
        public ActionResult Login()
        {
            Session["user"] = null;
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {
           
            var result = db.Users.Where(m => m.Username == user.Username && m.Password == user.Password).FirstOrDefault();
            if (result != null)
            {

                Session["user"] = result;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Message = string.Format("Username and Password is incorrect");
                return View();
            }
        }
    }
}

POS_APP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Main</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Assets/dist/css/adminlte.min.css">
    <!-- DataTable -->
    <link href="@Url.Content("~/Content/dataTables.bootstrap4.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap-select.min.css")" rel="stylesheet" />
    @RenderSection("styles", required: false)

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    @Html.Partial("_Navbar")
    @Html.Partial("_Sidebar")

    @RenderBody()


    <!-- jQuery -->
    <script src="~/Assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Assets/dist/js/adminlte.min.js"></script>
    <!-- DataTable -->
    <script src="@Url.Content("~/Scripts/jquery.noty.packaged.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.noty.packaged.min.js")"></script>


    <script src="@Url.Content("~/Scripts/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.bootstrap4.min.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery-ui.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-select.min.js")"></script>

    <script src="@Url.Content("~/Scripts/canvasjs.min.js")"></script>

    <script src="@Url.Content("~/Scripts/PrintReport.js")"></script>
    <script src="@Url.Content("~/Scripts/printThis.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

POS_APP/Views/Shared/_Navbar.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light fixed-top">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">

            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- User Profile -->
        @if (Session["user"] != null)
        {
            var user = (POS_APP.Models.User)Session["user"];

            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-sm-right dropdown-menu-right">
                    <span class="dropdown-item dropdown-header"> <i class="far fa-user-circle"></i> @Html.ActionLink(user.Username, "UserList", "Users")</span>

                    <div class="dropdown-divider"></div>
                    <span class="dropdown-item dropdown-header"> <i class="far fa-sign-out"></i> @Html.ActionLink("Logout", "Login", "Users", new { @class = "btn btn-warning" })</span>
                </div>
            </li>



            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
        }
        else
        {
            Response.Redirect(Url.Action("Login", "Users"));
        }





    </ul>
</nav>
<!-- /.navbar -->

POS_APP/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="@Url.Action("Index", "Home")" class="brand-link">
        <img src="~/Assets/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">POS</span>
    </a>
   
    <!-- Sidebar -->
    <div class="sidebar">


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                <li class="nav-header">REPORTS</li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li class="nav-header">MANAGE</li>

                <li class="nav-item">
                    <a href="@Url.Action("Index", "Sales")" class="nav-link">
                        <i class="nav-icon fas fa-store"></i>
                        <p>
                            POS
                           
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("UserList", "Users")" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            User Management
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-server"></i>
                        <p>
                            Product
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Products")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Product</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Categories")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Categories</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-store"></i>
                        <p>
                            Transaction
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                       <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Imports")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Import</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Vendors")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Supplier</p>
                            </a>
                        </li>
                    </ul>
                 
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-book"></i>
                        <p>
                            Report
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("SaleReport", "Reports")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Sale</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("StockReport", "Reports")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Stock</p>
                            </a>
                        </li>
                    </ul>

                </li>




            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

<script>
    var url = window.location;
    const allLinks = document.querySelectorAll('.nav-item a');
    const currentLink = [...allLinks].filter(e => {
        return e.href == url;
    });

    if (currentLink.length > 0) {
        currentLink[0].classList.add("active");
        currentLink[0].closest(".nav-treeview").style.display = "block";
        currentLink[0].closest(".has-treeview").classList.add("active");
    }
</script>